spring:
  application:
    name: board-api
  data:
    mongodb:
      uri: mongodb://board:board@localhost:27017/board?authSource=admin
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG